feature_columns:
  - "Load_Phase"
  - "Power"
  - "BR_pct"
  - "Bf"
  - "VO2"
  - "VO2_kg"
  - "VCO2"
  - "VCO2_kg"
  - "VE"
  - "VE_VO2"
  - "VE_VCO2"
  - "RER"
  - "HR"
  - "VO2_HR"
  - "PetCO2"
  - "PetO2"
  - "VT"
  - "Ti"
  - "Te"
  - "Ttot"
  - "Ti_Ttot_Ratio"
  - "VD_VT_Ratio"
  - "VT_Ti"
  - "SpO2"
  - "CHO_kcal_h"
  - "EE_kcal_h"
  - "CO"
  - "METS"

static_feature_columns:
  - "Age"
  - "Gender"
  - "Height_cm"
  - "Weight_kg"
