feature_columns:
  - "Load_Phase"
  - "Age"
  - "Gender"
  - "Height_cm"
  - "Weight_kg"
  - "BP_Diast"
  - "BP_Syst"
  - "BR_pct"
  - "Bf"
  - "CHO_kcal_h"
  - "CO"
  - "EE_kcal_h"
  - "HR"
  - "METS"
  - "PetCO2"
  - "PetO2"
  - "Power_Load"
  - "RER"
  - "SpO2"
  - "VCO2"
  - "VE"
  - "VE_VCO2"
  - "VE_VO2"
  - "VO2"
  - "VO2_HR"
  - "VO2_kg"
  - "VT"

# metadata_columns:
#   - "Load_Phase"
