include:
  - "${CONFIGS_DIR}/base/cpa_former.yaml"
  - "./base.yaml"

model:
  name: "cpa_former_v2_mtl"
  num_phases: 3
  num_centers: 3
  use_groupdro: true
  groupdro_eta: 0.05
  groupdro_momentum: 0.1
  groupdro_min_samples: 1
  groupdro_temperature: 1.0
  use_conv_frontend: true
  conv_kernel: 3
  conv_channels: 256
  primary_target_column: "VO2_kg_at_AT"
  aux_targets:
    time_at_at:
      target_column: "Time_at_AT"
      loss_weight: 0.25
    hr_at_at:
      target_column: "HR_at_AT"
      loss_weight: 0.25
  freeze_backbone: false
  backbone_strict: false

primary_target_column: "VO2_kg_at_AT"

target_columns:
  - VO2_kg_at_AT
  - Time_at_AT
  - HR_at_AT

center_columns:
  - Institute_Name
