include:
  - "./cpa_former.yaml"
  - "./base.yaml"

model:
  name: "cpa_former_v1"
  num_phases: 3
  num_centers: 3
  use_groupdro: true
  groupdro_eta: 0.05
  groupdro_momentum: 0.1
  groupdro_min_samples: 1
  groupdro_temperature: 1.0

target_columns:
  - VO2_kg_at_AT

center_columns:
  - Institute_Name
