include:
  - "./cpet_former.yaml"
  - "./base.yaml"

model:
  name: "cpet_former_v2"
  use_groupdro: true
  groupdro_eta: 0.05
  groupdro_momentum: 0.1
  groupdro_min_samples: 1
  groupdro_temperature: 1.0
  num_centers: 3
  primary_target_column: "VO2_kg_at_AT"
  freeze_backbone: false
  backbone_strict: false
  pretrained_backbone_path:

target_columns:
  - VO2_kg_at_AT

center_columns:
  - Institute_Name
